### PR TITLE
Added optional argument to getWeeksForMonth to set start day of week

### PR DESCRIPTION
**Pull request by nimzco**
First step to tackle: https://github.com/Shopify/polaris-react/issues/1738

### Context

In most of western countries calendar starts on Monday. In some other countries, it can even start on Saturday.

### What

- Adding extra parameter to `getWeeksForMonth()` to be able to pass the start week day.
- By default, if nothing is passed the behaviour stays the same.

### CODE REVIEW

**Comment by WillsonSmith** [comment]
I'd split out the config and package json updates to another PR

**Comment by nimzco** [comment]
You're right: ✨https://github.com/Shopify/javascript-utilities/pull/35

**Comment by nimzco** [comment]
I will keep all of the changes in different commit in this PR because I'm running into weird problem having it separated in another PR...

**Comment by nimzco** [comment]
Can you folks have a look today? 🚀

**Comment by nimzco** [comment]
@tzvipm @TheMallen Do you have time to have a look today?

**Comment by nimzco** [comment]
Thanks Mal!

**Pull request merged**
